### ISSUE TITLE
separate container?

### ISSUE THREAD

**Issue by brandontrue** [unhelpful7417/autobrr-no-rars#3]
First...THANK YOU for creating this!! I've been trying to deal with this for months now. 

Would there be a way to have this run as a separate docker container that's accessed via webhook? That way the autobrr container can remain updated in settings won't have to be duplicated. 

Happy to "buy you 5 coffees"!!

**Comment by unhelpful7417** [comment]
Glad to hear this might help get rid of some headaches for you! I honestly didn't expect anyone to find this project so I'm happy that at least one other person benefits.

Just to make sure I'm understanding you correctly, your main concern is that you don't want to have to reconfigure your autobrr settings if you use this image, correct? If so, then I think you're fine. You should be able to just swap out the container image in your `compose.yml` or CLI parameters from standard autobrr to this one. All this project does is take the latest autobrr release and bundle a script with it, so there really shouldn't be any changes from normal autobrr. If for some reason it does break, then you can just swap back to the regular autobrr image. Either way I'd appreciate you letting me know how that goes so I can update the documentation.

The only concern I can think of for using this image is that there will be a bit of lag when the latest autobrr image releases. I have a job running nightly to take the latest autobrr release and then build and push my image based on that, so at most there should be a 24 hour delay when new stuff is added to autobrr.

Side note: making this into something you can call with a webhook is a way better idea - hadn't thought of that when creating this. I think it'll work fine as it is since I'm 99% sure you can just swap the base image, but I think it'd be a good learning opportunity for me so I'm gonna play around with reworking this into some simple API. And while I appreciate you offering to pay me, don't worry about it. I'm getting to learn new stuff and help people out and that's enough for me.

Let me know if this works for you - thanks!

**Comment by brandontrue** [comment]
I'll give that a try and see how it goes.  Let me know if you want a tester!

**Comment by wolfday68** [comment]
did you remove this one altogether?  (autobrr pushed an update today but I don't see a rebuild here)

**Comment by unhelpful7417** [comment]
Nope, I'm gonna leave the current architecture as it is for now while I polish off the API version in the dev branch. As I mentioned my previous comment, this implementation kind of sucks because not only does it force you to use one specific version of autobrr, it has a lag between the latest autobrr release and when it gets rebuilt. I have the build pipeline running daily at 19:27 UTC so that rebuild for the main image should be happening in 2 hours.

The API version will resolve this by not caring about autobrr at all. All it does (currently) is receive a URL, download the torrent file at the URL, and inspect it for `.rar` files. So going forward, you'll run the normal autobrr image (at whatever version you like) and this API container, then tell autobrr to send a webhook to the API and verify it before downloading the torrent.

**Comment by wolfday68** [comment]
that sounds great!  also - it says there are no releases as of now (were they deleted?).  no worries on waiting until the pipeline build

**Comment by unhelpful7417** [comment]
They're published as packages onto the GitHub Container Registry, not releases. Check here: https://github.com/unhelpful7417/autobrr-no-rars/pkgs/container/autobrr-no-rars

**Comment by unhelpful7417** [comment]
> I'll give that a try and see how it goes. Let me know if you want a tester!

@brandontrue I think I've got it figured out. There's a new `compose.yml` on the dev branch with the updated API version. Try running that and set your autobrr external action to look like this:
![image](https://github.com/unhelpful7417/autobrr-no-rars/assets/116682787/5e543c2f-9c6c-484e-ba78-95df258f74e6)
Important thing is that the JSON data is `{ "url": "{{ .TorrentUrl }}" }`. Just copy and paste that in.

Let me know if you have any questions or issues.

**Comment by wolfday68** [comment]
okay I've had a chance to start testing and I'm running into an error:

`20:21:00DBGfilter external webhook response status: 400 body: {"detail":{"msg":"URL does not point to a .torrent file","url":"https://iptorrents.com/download.php/[REDACTED].torrent?torrent_pass=[REDACTED]"}} module=filter `

There are cases where it does work though:

`20:22:02DBGfilter external webhook response status: 200 body: {"msg":"No .rar files were found","url":"https://www.torrentleech.org/rss/download[REDACTED].torrent"} module=filter `

My guess is it's because the "?torrent_pass=" is appended at the end?

**Comment by unhelpful7417** [comment]
I knew that was gonna be an issue but thought I could get away with a lazy implementation. Easy fix - done.

**Comment by unhelpful7417** [comment]
Alright, I updated everything with the new API container and the old standalone version. They can now be found at the `:api` and `:standalone` image tags instead of `:dev` and `:main`. Documentation is updated as well. Closing this issue - thanks for all the input and help!
